### ISSUE TITLE
filtering fields (like Istartswith, gte, gt, ...) are required if mongoengine fields are also required

### ISSUE THREAD

**Issue by loic001** [riverfr0zen/graphene-mongo-extras#2]
First of all, thank you for your work.

`convert_mongoengine_field` function (used [here](https://github.com/riverfr0zen/graphene-mongo-extras/blob/4fdf84f6429d9c12eeb3558306ed4a2abae8a9d8/graphene_mongo_extras/filtering/__init__.py#L69)) copy the 'required' mongoengine field argument. This could be problematic because we do not want filter fields to be required as well.

**Comment by riverfr0zen** [comment]
Great catch, thanks.

Just pushed a fix. I had to resort to copying the mongoengine field; if you know of a better way let me know. Leaving this open for a while for any feedback.
