### ISSUE TITLE
Unable to upgrade to latest version

### ISSUE THREAD

**Issue by anilwarbhe** [riverfr0zen/graphene-mongo-extras#3]
I am trying to upgrade the package to the latest version but with no luck. would you please help me with how could I upgrade to 0.4.0.

**Comment by riverfr0zen** [comment]
Can you post how you are trying to upgrade it, and what errors you are getting?

**Comment by anilwarbhe** [comment]
I was trying to update it with the following command:
pip install https://github.com/riverfr0zen/graphene-mongo-extras.git
which was not working but 

The following one worked:
pip install git+https://github.com/riverfr0zen/graphene-mongo-extras.git
